apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-ctony
  namespace: ctony-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-ctony
  chart:
    git: https://github.com/TonyRowntree/bevel.git
    ref: feature/1749
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: ctony-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.ctony-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: ctonyMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: trownenvctony-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/ctony-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/ctony-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      Ct0CChgKFggCGgYI0tvHjQYiCmFsbGNoYW5uZWwSwAIKvQIKCmFsbGNoYW5uZWwSYRJfCgtBcHBs
      aWNhdGlvbhJQCAESTAoIY3RvbnlNU1ASQBoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRvcnNl
      bWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAaywESyAEKC0FwcGxpY2F0aW9uErgBCAES
      swEKCGN0b255TVNQEqYBCAEaWgoLQW5jaG9yUGVlcnMSSxJBCj8KOnBlZXIwLmN0b255LW5ldC5o
      Zi5kZXYyLmF3cy5ibG9ja2NoYWluY2xvdWRwb2MtZGV2ZWxvcC5jb20Q+0EaBkFkbWlucxoHCgNN
      U1ASACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5z
      EgAqBkFkbWlucw==

