apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: trown-cacerts-job
  namespace: trown-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: trown-cacerts-job
  chart:
    git: https://github.com/TonyRowntree/bevel.git
    ref: feature/1749
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: trown
      component_name: trown-net
      namespace: trown-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: trownenvtrown-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/trown-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/trown-net/ca/trown
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.trown-net
