apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-tony2-allchannel-supplychain1-1
  namespace: tony2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-tony2-allchannel-supplychain1-1
  chart:
    git: https://github.com/TonyRowntree/bevel.git
    ref: feat-1749
    path: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: tony2-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.tony2-net:7051
      localmspid: tony2MSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: tonyenvtony2-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/tony2-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/tony2-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: tony2-net
      name:  tony2  
      corepeeraddress:  peer0.tony2-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443 
