apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ctrown-cacerts-job
  namespace: ctrown-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ctrown-cacerts-job
  chart:
    git: https://github.com/TonyRowntree/bevel.git
    ref: feature/1749
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: ctrown
      component_name: ctrown-net
      namespace: ctrown-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: trownenvctrown-net-auth
      secretcryptoprefix: secretsv2/data/crypto/peerOrganizations/ctrown-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/ctrown-net/ca/ctrown
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Carrier/CN=ca.ctrown-net
